### PR TITLE
Script should not modify itself; better error exposure

### LINKED ISSUE #16: Better script error logging
#### Description:

- Add a general try-catch block to print out exceptions
- Bat script should pause before closing the window once execution is finished, so errors can be displayed.

### LINKED ISSUE #17: Powershell script should not modify itself
#### Description:

Currently the powershell script also modifies its own content, replacing `AdapterName` in the code text once it is run.

### PR DESCRIPTION
**Pull request by alelom**
### Issues addressed by this PR

Closes #16
Closes #17

Let's see if this PR also helps with #15.

### CODE REVIEW

**Review by michaelhoehn — CHANGES_REQUESTED** [review]
This renamed everything correctly in the file structure, but did not rename in the solution file 😕 

image

**Comment by alelom** [comment]
@michaelhoehn Did you get any error? Could you try this again and paste a screenshot of the entire console dump? With this PR, the console should pause before closing once the run is finished.

Really keen to see what's wrong here -- script has always worked reliably for me and others, first time I see these problems.

**Review by michaelhoehn — DISMISSED** [review]
After chatting through the process together, it's clear I can't replicate the issue anymore for some unknown reason. Happy to see this merged since it adds some nice log functionality. Thanks @alelom

**Review by michaelhoehn — APPROVED** [review]
Happy with the updates to the readme.md

**Pull request merged**
